### ISSUE TITLE
Base Requirements 

### ISSUE THREAD

**Issue by martin-migal** [hubner-lab/GWANN#1]
Hi Nimrod, Martin here.
Haven't successfully run the project yet, but to get started, I'm wondering whether the base project depends specifically on Python 3.8. 
Also, would you prefer that I alert you to issues or try and make pull requests?

(to name specific requirement issues: under python3.6 project requirements fail. also without cuda requirements fail)

Thanks :)

**Comment by hubner-lab** [comment]
I prefer you make pull requests.
Thanks
