### ISSUE TITLE
Issue in simulation process

### ISSUE THREAD

**Issue by Jyoti-Jittu** [hubner-lab/GWANN#5]
Hello..

This is really a great paper 

I have successfully installed GWANN and all its requirements. However, I am facing an issue while simulating data...
While it does not display any errors, it also does not generate any data. It only generates 0 kb files. 

Can you help me with this matter?

**Comment by martin-migal** [comment]
Sorry for the delay. The current version does not return an error when simulation fails. Apologies, this is scheduled to be fixed.
That said, the current version assumes that "Whole Genome Simulator" is available in the root directory, under the executable name "genome". That might be the problem.

**Comment by Jyoti-Jittu** [comment]
Thank you... Now it is working.
